# Generated by Django 5.2.17 on 2026-09-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvedarticlelog",
            name="logged_at",
        ),
        migrations.RemoveField(
            model_name="approvedarticlelog",
            name="payload",
        ),
    ]
