# Generated by Django 5.2.17 on 2026-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="newsletters/"
            ),
        ),
    ]
