# Generated by Django 5.2.17 on 2026-10-03 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_article_thumbnail_newsletter_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvedarticlelog",
            options={"ordering": ["-logged_at"]},
        ),
        migrations.AddField(
            model_name="approvedarticlelog",
            name="logged_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="approvedarticlelog",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
